# Generated by Django 4.2.7 on 2023-11-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegHuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('address', models.PositiveIntegerField()),
                ('favorite_music', models.CharField(max_length=50)),
                ('favorite_hobbies', models.CharField(max_length=255)),
                ('favorite_anime', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='human',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
